apiVersion: v1
kind: Service
metadata:
  name: poojitha-service-1
  labels:
    app: poojitha-app
spec:
  selector:
    app: poojitha-app
  ports:
    - name: container-1
      protocol: TCP
      port: 80
      targetPort: 6000
  type: LoadBalancer
